spring:
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

server:
  port: ${PORT:9090}

app:
  init:
    admin:
      enabled: ${INIT_ADMIN_ENABLED:false}
      email: ${INIT_ADMIN_EMAIL:}
      password: ${INIT_ADMIN_PASSWORD:}
      full-name: ${INIT_ADMIN_FULL_NAME:System Admin}
  analytics:
    enabled: ${ANALYTICS_ENABLED:false}

logging:
  level:
    org.springframework.security: INFO
    org.springframework.web: INFO
